/** Declaration file generated by dts-gen */

export = koa_socket_2;

declare class koa_socket_2 {
    constructor(...args: any[]);

    attach(...args: any[]): void;

    attachNamespace(...args: any[]): void;

    broadcast(...args: any[]): void;

    off(...args: any[]): this;

    on(...args: any[]): this;

    onConnection(...args: any[]): void;

    onDisconnect(...args: any[]): void;

    to(...args: any[]): void;

    updateConnections(...args: any[]): void;

    use(...args: any[]): void;

}

