import { queryResult } from "../bin/interface";
import Axios from "axios";

function AriTestData(): queryResult[] {
  const timeStamp = Date.now();
  const time = new Date().toString();
  return [
    {
      content: "0104001c001ab007",
      mac: "866262045427977",
      pid: 1,
      timeStamp,
      buffer: {
        data: [
          1,
          4,
          52,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          226,
          103
        ],
        type: "Buffer"
      },
      protocol: "卡乐控制器",

      stat: "success",
      time,
      type: 485
    },
    {
      content: "0104002f004241f2",
      mac: "866262045427977",
      pid: 1,
      timeStamp,
      buffer: {
        data: [
          1,
          4,
          132,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          109,
          230
        ],
        type: "Buffer"
      },
      protocol: "卡乐控制器",

      stat: "success",
      time,
      type: 485
    },
    {
      content: "01040029000c21c7",
      mac: "866262045427977",
      pid: 1,
      timeStamp,
      buffer: {
        data: [
          1,
          4,
          24,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          130,
          139
        ],
        type: "Buffer"
      },
      protocol: "卡乐控制器",

      stat: "success",
      time,
      type: 485
    },
    {
      content: "01040001001be1c1",
      mac: "866262045427977",
      pid: 1,
      timeStamp,
      buffer: {
        data: [
          1,
          4,
          54,
          216,
          241,
          216,
          241,
          216,
          241,
          216,
          241,
          216,
          241,
          0,
          0,
          255,
          231,
          255,
          198,
          255,
          198,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          9,
          181
        ],
        type: "Buffer"
      },
      protocol: "卡乐控制器",

      stat: "success",
      time,
      type: 485
    },
    // TH
    {
      pid : 0,
      stat : "success",
      buffer : {
        data : [
          0,
          3,
          4,
          0,
          50,
          2,
          215,
          44,
          33
        ],
        type : "Buffer"
      },
      timeStamp,
      time,
      mac : "866262045427977",
      type : 485,
      protocol : "温湿度1",
      content : "000300000002c5da",
      
    }
    
  ];
}
setInterval(()=>{
  Axios.post("http://127.0.0.1:9010/Api/Node/UartData", { data: AriTestData() })
  .then(e => console.log(e.data))
  .catch(e => console.log(e));
},10000)


